version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    depends_on:
      - client
    ports:
      - "8080:8080"
